language: python
python:
  - "2.7"
  - "3.5"
  
install:
  - pip install coveralls

script:
  #- python hello.py
  - coverage run hello.py

after_success:
  COVERALLS_REPO_TOKEN=J3DfcedH0RlsDSIEmuFytF0fW8odRbgbW coverage
